tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "wader/tap"
brew "afio"
brew "webp"
brew "arping"
brew "icu4c"
brew "boost"
brew "docbook"
brew "sqlite"
brew "xz"
brew "asciidoc"
brew "gettext"
brew "python@3.9"
brew "glib"
brew "atomicparsley"
brew "atool"
brew "autoconf"
brew "automake"
brew "azure-cli"
brew "bchunk"
brew "binaryen"
brew "blueutil"
brew "brew-gem"
brew "cabextract"
brew "freetype"
brew "fontconfig"
brew "cairo"
brew "gmp"
brew "gcc"
brew "openblas"
brew "cgdb"
brew "clamav"
brew "cmake"
brew "cmigemo"
brew "coreutils"
brew "cowsay"
brew "croc"
brew "cscope"
brew "ctags"
brew "ddrescue"
brew "deno"
brew "dfc"
brew "diff-so-fancy"
brew "docker", link: false
brew "emojify"
brew "node"
brew "openjdk"
brew "emscripten"
brew "exiftool"
brew "exiv2"
brew "fcrackzip"
brew "fribidi"
brew "p11-kit"
brew "gnutls"
brew "harfbuzz"
brew "lame"
brew "openjpeg"
brew "x264"
brew "x265"
brew "xvid"
brew "ffmpeg"
brew "figlet"
brew "fortune"
brew "fzf"
brew "fzy"
brew "git"
brew "gnupg"
brew "go"
brew "graphviz"
brew "handbrake", link: false
brew "hashcat"
brew "hdf5"
brew "lua"
brew "highlight"
brew "htop"
brew "icoutils"
brew "imagemagick"
brew "john-jumbo"
brew "jq"
brew "kotlin"
brew "leveldb"
brew "lha"
brew "libdvdcss"
brew "libgit2"
brew "librtlsdr"
brew "lima"
brew "llvm"
brew "lsusb"
brew "m-cli"
brew "macvim"
brew "mas"
brew "mdf2iso"
brew "mosh"
brew "mosquitto"
brew "mutt"
brew "nasm"
brew "neomutt"
brew "neovim"
brew "newt"
brew "nginx"
brew "nkf"
brew "nmap"
brew "nodenv"
brew "numpy"
brew "opencv"
brew "p7zip"
brew "pandoc"
brew "parallel"
brew "pdfcrack"
brew "peco"
brew "pv"
brew "pyenv"
brew "r"
brew "rsync"
brew "rtl_433"
brew "rustup-init"
brew "sl"
brew "testdisk"
brew "the_silver_searcher"
brew "thefuck"
brew "tmux"
brew "transmission-cli"
brew "tree"
brew "w3m"
brew "wasmer"
brew "watchman"
brew "wget"
brew "winetricks"
brew "yarn"
brew "yasm"
brew "youtube-dl"
brew "yt-dlp"
brew "zbar"
brew "zenity"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "wader/tap/fq"
cask "adobe-acrobat-pro"
cask "adobe-acrobat-reader"
cask "aldente"
cask "android-studio"
cask "appcleaner"
cask "arduino"
cask "arduino-ide-beta"
cask "atok"
cask "audacity"
cask "bartender"
cask "bathyscaphe"
cask "betterzip"
cask "blender"
cask "boxofsnoo-fairmount"
cask "burn"
cask "caffeine"
cask "calibre"
cask "clipy"
cask "color-oracle"
cask "cubicsdr"
cask "deepl"
cask "docker"
cask "duet"
cask "firefox"
cask "font-fira-code"
cask "font-ipaexfont"
cask "forklift"
cask "ghidra"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "gpower"
cask "gqrx"
cask "grandperspective"
cask "hammerspoon"
cask "handbrake"
cask "iina"
cask "imageoptim"
cask "inkscape"
cask "iterm2"
cask "joplin"
cask "karabiner-elements"
cask "keepassxc"
cask "keka"
cask "kindle"
cask "kindle-comic-converter"
cask "kindle-previewer"
cask "kodi"
cask "krita"
cask "lyrics-master"
cask "macdown"
cask "macgdbp"
cask "mactex"
cask "mark-text"
cask "meld"
cask "mendeley"
cask "menumeters"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "monitorcontrol"
cask "musescore"
cask "openemu"
cask "osirix-quicklook"
cask "powershell"
cask "qgis"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "rar"
cask "rstudio"
cask "sdrdx"
cask "sequel-pro"
cask "smartgit"
cask "sourcetree"
cask "steam"
cask "suspicious-package"
cask "tigervnc-viewer"
cask "tomighty"
cask "touch-bar-simulator"
cask "transmission"
cask "tripmode"
cask "unofficial-wineskin"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "wine-crossover"
cask "xld"
cask "xquartz"
cask "zoom"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Affinity Publisher", id: 881418622
mas "App Language Chooser", id: 451732904
mas "CotEditor", id: 1024640650
mas "Developer", id: 640199958
mas "Display Menu", id: 549083868
mas "EdgeView", id: 1580323719
mas "EdgeView 2", id: 1206246482
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1444383602
mas "Hex Fiend", id: 1342896380
mas "iMovie", id: 408981434
mas "isHUD", id: 484757536
mas "Keepa - Price Tracker", id: 1533805339
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LadioCast", id: 411213048
mas "LibreOffice Vanilla", id: 921923693
mas "LINE", id: 539883307
mas "Logic Pro", id: 634148309
mas "Magnet", id: 441258766
mas "MainStage", id: 634159523
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Motion", id: 434290957
mas "Native SQLite Manager", id: 1416282836
mas "Noizio", id: 928871589
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PDF Squeezer 3", id: 504700302
mas "PDFOutliner", id: 420874236
mas "PopClip", id: 445189367
mas "Prime Video", id: 545519333
mas "The Unarchiver", id: 425424353
mas "TinyStopwatch", id: 1447754003
mas "uBlacklist for Safari", id: 1547912640
mas "WiFi Signal", id: 525912054
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
