version: '3.9' # Docker Engine version
services:
  app:
    container_name: myapp
    image: myapp:latest
    volumes:
      - type: bind
        source: ./app
        target: /app
    command: python app.py
  db:
    container_name: mydb
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - type: volumes
        source: VOLUME_NAME
        target: /var/lib/mysql
    ports:
      - "LOCAL_PORT:CONTAINER_PORT"
volumes:
  VOLUME_NAME:
